export type Countries = {
  id: string;
  name: string;
  tip: string;
  flag: string;
};

export const COUNTRIES_DATA: Countries[] = [
  {
    id: "BR",
    name: "Brasil",
    tip: "É conhecido pelo carnaval e samba.",
    flag: "https://flagpedia.net/data/flags/w580/br.webp",
  },
  {
    id: "JP",
    name: "Japao",
    tip: "Conhecido como a Terra do Sol Nascente e pelo sushi.",
    flag: "https://flagpedia.net/data/flags/w580/jp.webp",
  },
  {
    id: "IT",
    name: "Italia",
    tip: "Famosa por sua culinária, como pizza e massas, e pelo Coliseu.",
    flag: "https://flagpedia.net/data/flags/w580/it.webp",
  },
  {
    id: "FR",
    name: "Franca",
    tip: "Abriga a Torre Eiffel e é famosa por seus vinhos e queijos.",
    flag: "https://flagpedia.net/data/flags/w580/fr.webp",
  },
  {
    id: "AR",
    name: "Argentina",
    tip: "Conhecida pelo tango, alfajor e grande paixão pelo futebol.",
    flag: "https://flagpedia.net/data/flags/w580/ar.webp",
  },
  {
    id: "MX",
    name: "Mexico",
    tip: "Terra dos mariachis, da culinária apimentada e de Chichén Itzá.",
    flag: "https://flagpedia.net/data/flags/w580/mx.webp",
  },
  {
    id: "AU",
    name: "Australia",
    tip: "Famosa por sua vida selvagem única, com cangurus e coalas.",
    flag: "https://flagpedia.net/data/flags/w580/au.webp",
  },
  {
    id: "DE",
    name: "Alemanha",
    tip: "Conhecida pela Oktoberfest, grandes castelos e indústria automotiva.",
    flag: "https://flagpedia.net/data/flags/w580/de.webp",
  },
  {
    id: "EG",
    name: "Egito",
    tip: "Abriga construções milenares no deserto e o imponente Rio Nilo.",
    flag: "https://flagpedia.net/data/flags/w580/eg.webp",
  },
  {
    id: "CA",
    name: "Canada",
    tip: "Famoso pelo xarope de bordo (maple syrup) e por suas folhas vermelhas.",
    flag: "https://flagpedia.net/data/flags/w580/ca.webp",
  },
  {
    id: "PT",
    name: "Portugal",
    tip: "Terra do pastel de nata e grandes navegadores históricos.",
    flag: "https://flagpedia.net/data/flags/w580/pt.webp",
  },
  {
    id: "ES",
    name: "Espanha",
    tip: "Conhecida pela dança flamenca e pela paella.",
    flag: "https://flagpedia.net/data/flags/w580/es.webp",
  },
  {
    id: "CN",
    name: "China",
    tip: "Lar da Grande Muralha e dos ursos panda.",
    flag: "https://flagpedia.net/data/flags/w580/cn.webp",
  },
  {
    id: "IN",
    name: "India",
    tip: "Famosa pelo Taj Mahal, por Bollywood e culinária temperada.",
    flag: "https://flagpedia.net/data/flags/w580/in.webp",
  },
  {
    id: "RU",
    name: "Russia",
    tip: "O maior país do mundo, famoso pelo frio e pela Praça Vermelha.",
    flag: "https://flagpedia.net/data/flags/w580/ru.webp",
  },
  {
    id: "TR",
    name: "Turquia",
    tip: "País que divide Europa e Ásia, famoso pelos balões da Capadócia.",
    flag: "https://flagpedia.net/data/flags/w580/tr.webp",
  },
  {
    id: "CH",
    name: "Suica",
    tip: "Famosa pelos Alpes, relógios de precisão e chocolates.",
    flag: "https://flagpedia.net/data/flags/w580/ch.webp",
  },
  {
    id: "SE",
    name: "Suecia",
    tip: "Terra dos vikings modernos, do prêmio Nobel e da loja IKEA.",
    flag: "https://flagpedia.net/data/flags/w580/se.webp",
  },
  {
    id: "NO",
    name: "Noruega",
    tip: "Famosa por seus fiordes impressionantes e aurora boreal.",
    flag: "https://flagpedia.net/data/flags/w580/no.webp",
  },
  {
    id: "FI",
    name: "Finlandia",
    tip: "Conhecida como a casa do Papai Noel e por suas milhares de saunas.",
    flag: "https://flagpedia.net/data/flags/w580/fi.webp",
  },
  {
    id: "DK",
    name: "Dinamarca",
    tip: "Terra onde o LEGO foi inventado e conhecida pelos ciclistas.",
    flag: "https://flagpedia.net/data/flags/w580/dk.webp",
  },
  {
    id: "NL",
    name: "Holanda",
    tip: "Famosa pelos moinhos de vento, tulipas e canais de Amsterdã.",
    flag: "https://flagpedia.net/data/flags/w580/nl.webp",
  },
  {
    id: "BE",
    name: "Belgica",
    tip: "Sede da União Europeia, famosa por chocolates, waffles e batatas fritas.",
    flag: "https://flagpedia.net/data/flags/w580/be.webp",
  },
  {
    id: "GR",
    name: "Grecia",
    tip: "Berço da democracia, das Olimpíadas e da mitologia antiga.",
    flag: "https://flagpedia.net/data/flags/w580/gr.webp",
  },
  {
    id: "IE",
    name: "Irlanda",
    tip: "A Ilha Esmeralda, famosa por seus pubs, duendes e o trevo da sorte.",
    flag: "https://flagpedia.net/data/flags/w580/ie.webp",
  },
  {
    id: "CO",
    name: "Colombia",
    tip: "Maior produtor mundial de esmeraldas e famosa pelo seu café.",
    flag: "https://flagpedia.net/data/flags/w580/co.webp",
  },
  {
    id: "PE",
    name: "Peru",
    tip: "Abriga a cidade perdida dos Incas, Machu Picchu.",
    flag: "https://flagpedia.net/data/flags/w580/pe.webp",
  },
  {
    id: "CL",
    name: "Chile",
    tip: "O país mais longo do mundo, abriga o deserto do Atacama.",
    flag: "https://flagpedia.net/data/flags/w580/cl.webp",
  },
  {
    id: "UY",
    name: "Uruguai",
    tip: "Pequeno país sul-americano famoso pela carne e pelo chimarrão (mate).",
    flag: "https://flagpedia.net/data/flags/w580/uy.webp",
  },
  {
    id: "VE",
    name: "Venezuela",
    tip: "Lar da queda d'água mais alta do mundo, o Salto Ángel.",
    flag: "https://flagpedia.net/data/flags/w580/ve.webp",
  },
  {
    id: "CU",
    name: "Cuba",
    tip: "Ilha do Caribe famosa por seus carros antigos e charutos.",
    flag: "https://flagpedia.net/data/flags/w580/cu.webp",
  },
  {
    id: "JM",
    name: "Jamaica",
    tip: "Berço do reggae, de Bob Marley e de grandes corredores.",
    flag: "https://flagpedia.net/data/flags/w580/jm.webp",
  },
  {
    id: "MA",
    name: "Marrocos",
    tip: "Porta de entrada do Saara, conhecido pelos seus mercados coloridos (souks).",
    flag: "https://flagpedia.net/data/flags/w580/ma.webp",
  },
  {
    id: "NG",
    name: "Nigeria",
    tip: "A economia mais populosa da África, famosa pela indústria cinematográfica Nollywood.",
    flag: "https://flagpedia.net/data/flags/w580/ng.webp",
  },
  {
    id: "KE",
    name: "Quenia",
    tip: "Destino principal de safáris e lar de grandes maratonistas mundiais.",
    flag: "https://flagpedia.net/data/flags/w580/ke.webp",
  },
  {
    id: "TH",
    name: "Tailandia",
    tip: "Conhecida como a Terra dos Sorrisos, cheia de templos e belas praias.",
    flag: "https://flagpedia.net/data/flags/w580/th.webp",
  },
  {
    id: "VN",
    name: "Vietna",
    tip: "Famoso por sua comida de rua, pelo chapéu cônico e pela Baía de Halong.",
    flag: "https://flagpedia.net/data/flags/w580/vn.webp",
  },
  {
    id: "PH",
    name: "Filipinas",
    tip: "Um arquipélago com mais de 7 mil ilhas e belas águas tropicais.",
    flag: "https://flagpedia.net/data/flags/w580/ph.webp",
  },
  {
    id: "ID",
    name: "Indonesia",
    tip: "O maior arquipélago do mundo, abriga a famosa ilha de Bali.",
    flag: "https://flagpedia.net/data/flags/w580/id.webp",
  },
  {
    id: "MY",
    name: "Malasia",
    tip: "Onde ficam as famosas Torres Petronas, as mais altas torres gêmeas do mundo.",
    flag: "https://flagpedia.net/data/flags/w580/my.webp",
  },
  {
    id: "SG",
    name: "Singapura",
    tip: "Cidade-estado com leis rígidas de limpeza e um aeroporto luxuoso.",
    flag: "https://flagpedia.net/data/flags/w580/sg.webp",
  },
  {
    id: "IL",
    name: "Israel",
    tip: "Considerada a Terra Santa por várias religiões e banhada pelo Mar Morto.",
    flag: "https://flagpedia.net/data/flags/w580/il.webp",
  },
  {
    id: "PL",
    name: "Polonia",
    tip: "Famosa por sua rica história medieval e por ser o berço do cientista Copérnico.",
    flag: "https://flagpedia.net/data/flags/w580/pl.webp",
  },
];
